In [1]:
import sys
sys.path.append("../") # go to parent dir

from load_data import load_data
from distance import total_variation_distance
from test_instances.ts_test import TSTest
from test_instances.fair_sd_ts_test import FairSDTest
from test_instances.sd_ts_test import SDTest
import numpy as np
import test_instances.plots as test
import sys


In [2]:
N_ITERATIONS = 100.
DATA_SET = ['Bar Exam', 'Default on Credit'][0]
bandits = load_data(DATA_SET)

In [3]:
T = 100
e1 = [2]
e2 = [0.]
delta = [0.]


In [4]:
sd_test = SDTest(N_ITERATIONS, bandits, T, e1, e2, delta, lam=1, distance=total_variation_distance)
sd_test.analyse(fair_regret = False, regret=False, subjective_smooth_fair=True, smooth_fair=False ) 

i1
j4
1.38777878078e-17
i4
j1
1.38777878078e-17
i1
j4
8.32667268469e-17
i4
j1
8.32667268469e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i0
j3
6.93889390391e-17
i3
j0
6.93889390391e-17
i1
j3
1.38777878078e-17
i3
j1
1.38777878078e-17
i1
j4
1.38777878078e-17
i2
j4
1.38777878078e-17
i4
j1
1.38777878078e-17
i4
j2
1.38777878078e-17
i1
j4
6.93889390391e-17
i2
j4
6.93889390391e-17
i4
j1
6.93889390391e-17
i4
j2
6.93889390391e-17
i1
j4
1.38777878078e-17
i2
j4
1.38777878078e-17
i4
j1
1.38777878078e-17
i4
j2
1.38777878078e-17
i1
j4
1.38777878078e-17
i2
j4
1.38777878078e-17
i4
j1
1.38777878078e-17
i4
j2
1.38777878078e-17
i1
j4
1.38777878078e-17
i2
j4
1.38777878078e-17
i4
j1
1.38777878078e-17
i4
j2
1.38777878078e-17
i2
j4
1.38777878078e-17
i4
j2
1.38777878078e-17
i2
j3
1.38777878078e-17
i3
j2
1.38777878078e-17
i0
j4
2.77555756156e-17
i4
j0
2.77555756156e-17
i0
j4
2.77555756156e-17
i4
j0
2.77555756156e-17
i0
j4
1.38777878078e-17
i4
j0
1.38777878078e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878

j2
6.93889390391e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i1
j4
1.38777878078e-17
i4
j1
1.38777878078e-17
i1
j3
1.38777878078e-17
i3
j1
1.38777878078e-17
i0
j3
8.32667268469e-17
i3
j0
8.32667268469e-17
i0
j4
1.38777878078e-17
i4
j0
1.38777878078e-17
i0
j4
6.93889390391e-17
i4
j0
6.93889390391e-17
i1
j3
1.38777878078e-17
i3
j1
1.38777878078e-17
i1
j3
1.38777878078e-17
i3
j1
1.38777878078e-17
i0
j2
6.93889390391e-17
i2
j0
6.93889390391e-17
i1
j4
8.32667268469e-17
i4
j1
8.32667268469e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i0
j3
2.77555756156e-17
i3
j0
2.77555756156e-17
i2
j4
2.77555756156e-17
i4
j2
2.77555756156e-17
i0
j4
1.38777878078e-17
i1
j4
1.38777878078e-17
i2
j4
1.38777878078

j1
1.38777878078e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i2
j3
1.38777878078e-17
i3
j2
1.38777878078e-17
i0
j3
6.93889390391e-17
i3
j0
6.93889390391e-17
i0
j3
6.93889390391e-17
i3
j0
6.93889390391e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i0
j2
1.38777878078e-17
i2
j0
1.38777878078e-17
i1
j4
2.77555756156e-17
i4
j1
2.77555756156e-17
i0
j3
8.32667268469e-17
i3
j0
8.32667268469e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i3
j4
1.38777878078e-17
i4
j3
1.38777878078e-17
i0
j2
2.77555756156e-17
i2
j0
2.77555756156e-17
i0
j2
2.77555756156e-17
i0
j3
2.77555756156e-17
i2
j0
2.77555756156e-17
i3
j0
2.77555756156e-17
i2
j3
1.38777878078e-17
i3
j2
1.38777878078e-17
i2
j4
2.77555756156e-17
i4
j2
2.77555756156e-17
i2
j4
8.32667268469e-17
i4
j2
8.32667268469e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i0
j4
2.77555756156e-17
i4
j0
2.77555756156e-17
i0
j4
1.38777878078

i2
j4
6.93889390391e-17
i3
j0
1.38777878078e-17
i4
j2
6.93889390391e-17
i2
j4
2.77555756156e-17
i4
j2
2.77555756156e-17
i2
j4
6.93889390391e-17
i4
j2
6.93889390391e-17
i2
j4
1.38777878078e-17
i4
j2
1.38777878078e-17
i1
j3
1.38777878078e-17
i3
j1
1.38777878078e-17
i1
j3
1.38777878078e-17
i3
j1
1.38777878078e-17
i0
j3
1.38777878078e-17
i0
j4
1.38777878078e-17
i1
j3
1.38777878078e-17
i1
j4
1.38777878078e-17
i3
j0
1.38777878078e-17
i3
j1
1.38777878078e-17
i4
j0
1.38777878078e-17
i4
j1
1.38777878078e-17
i1
j3
1.38777878078e-17
i3
j1
1.38777878078e-17
i0
j3
8.32667268469e-17
i3
j0
8.32667268469e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i0
j3
1.38777878078e-17
i3
j0
1.38777878078e-17
i2
j4
1.38777878078e-17
i4
j2
1.38777878078e-17
i1
j4
1.38777878078e-17
i4
j1
1.38777878078e-17
i1
j3
1.38777878078e-17
i3
j1
1.38777878078e-17
i3
j4
6.93889390391e-17
i4
j3
6.93889390391e-17
i0
j3
8.32667268469e-17
i3
j0
8.32667268469e-17
i0
j3
1.38777878

In [5]:
print sd_test.smooth_fair

[[[[[ 100.  100.  100.  100.  100.]
    [ 100.  100.  100.  100.  100.]
    [ 100.  100.  100.  100.  100.]
    [ 100.  100.  100.  100.  100.]
    [ 100.  100.  100.  100.  100.]]

   [[ 100.  100.   79.   64.   60.]
    [ 100.  100.  100.   85.   81.]
    [  79.  100.  100.  100.   96.]
    [  64.   85.  100.  100.  100.]
    [  60.   81.   96.  100.  100.]]

   [[ 100.  100.  100.   97.   97.]
    [ 100.  100.  100.   97.   97.]
    [ 100.  100.  100.  100.  100.]
    [  97.   97.  100.  100.  100.]
    [  97.   97.  100.  100.  100.]]

   ..., 
   [[ 100.  100.  100.  100.   99.]
    [ 100.  100.  100.  100.  100.]
    [ 100.  100.  100.  100.  100.]
    [ 100.  100.  100.  100.  100.]
    [  99.  100.  100.  100.  100.]]

   [[ 100.  100.  100.  100.  100.]
    [ 100.  100.  100.  100.  100.]
    [ 100.  100.  100.   99.  100.]
    [ 100.  100.   99.  100.  100.]
    [ 100.  100.  100.  100.  100.]]

   [[ 100.  100.  100.  100.   99.]
    [ 100.  100.  100.  100.  100.]
    [ 100

In [6]:
print sd_test.frac_smooth_fair

[[[[[ 1.    1.    1.    1.    1.  ]
    [ 1.    1.    1.    1.    1.  ]
    [ 1.    1.    1.    1.    1.  ]
    [ 1.    1.    1.    1.    1.  ]
    [ 1.    1.    1.    1.    1.  ]]]]



 [[[[ 1.    1.    0.79  0.64  0.6 ]
    [ 1.    1.    1.    0.85  0.81]
    [ 0.79  1.    1.    1.    0.96]
    [ 0.64  0.85  1.    1.    1.  ]
    [ 0.6   0.81  0.96  1.    1.  ]]]]



 [[[[ 1.    1.    1.    0.97  0.97]
    [ 1.    1.    1.    0.97  0.97]
    [ 1.    1.    1.    1.    1.  ]
    [ 0.97  0.97  1.    1.    1.  ]
    [ 0.97  0.97  1.    1.    1.  ]]]]



 ..., 
 [[[[ 1.    1.    1.    1.    0.99]
    [ 1.    1.    1.    1.    1.  ]
    [ 1.    1.    1.    1.    1.  ]
    [ 1.    1.    1.    1.    1.  ]
    [ 0.99  1.    1.    1.    1.  ]]]]



 [[[[ 1.    1.    1.    1.    1.  ]
    [ 1.    1.    1.    1.    1.  ]
    [ 1.    1.    1.    0.99  1.  ]
    [ 1.    1.    0.99  1.    1.  ]
    [ 1.    1.    1.    1.    1.  ]]]]



 [[[[ 1.    1.    1.    1.    0.99]
    [ 1.    1.    1.    1. 

In [7]:
print sd_test.is_smooth_fair

[[[[ 1.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]


 [[[ 0.]]]

